name: Node.js CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build and Test Node.js App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧱 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🧪 Run Tests
        run: npm test || echo "No tests defined"

      - name: 🚀 Run Build (if any)
        run: |
          if [ -f package.json ] && grep -q build package.json; then
            npm run build
          else
            echo "No build step defined"
          fi
